### ISSUE TITLE
Images for pyvo.cz

### ISSUE THREAD

**Issue by encukou** [pyvec/pyvo-resources#2]
Could you draw the following images for pyvo.cz?

> ![icons-small](https://cloud.githubusercontent.com/assets/302922/8389121/e8b90d50-1c6b-11e5-9591-119b50d97129.png)

They should scale from 200x200px down to 3em (~50px). The large size looks like this:

> ![icons-big](https://cloud.githubusercontent.com/assets/302922/8389123/ef10ec5e-1c6b-11e5-8f15-83cdaa9b282b.png)

My rough sketches are here: https://github.com/pyvec/pyvo.cz/tree/master/pyvocz/static/images

**Comment by honzajavorek** [comment]
:+1: Related to https://github.com/pyvec/pyvo.cz/issues/9.

**Comment by honzajavorek** [comment]
Closed by 1c47085eb8f3184b75cc25defa831e8d8ce7eb93.
